# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Numero_Habitacion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descripcion', models.TextField()),
                ('Estado', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='Categoria.categoria')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitaciones',
            },
        ),
    ]
