# Generated by Django 4.2.21 on 2026-05-21 03:55

from django.db import migrations, models

def seed_data(apps, schema_editor):
    Categoria = apps.get_model('Categoria', 'Categoria')
    Habitacion = apps.get_model('Habitacion', 'Habitacion')
    # Reset tables
    Categoria.objects.all().delete()
    Habitacion.objects.all().delete()
    # Create categories
    categorias = [
        (1, 'Estandar'),
        (2, 'Familiar'),
        (3, 'Premium'),
    ]
    for id_cat, nombre in categorias:
        Categoria.objects.update_or_create(id_categoria=id_cat, defaults={'NombreCategoria': nombre})

    # Create rooms
    habitaciones = [
        (1,1,1,500,"2 camas, Matrimonial e Individual, Baño privado"),
        (2,1,2,500,"2 camas, Matrimonial e Individual, Baño privado"),
        (3,1,3,400,"Cama matrimonial, Baño privado"),
        (4,1,4,500,"2 camas Individuales, Baño privado"),
        (5,1,5,400,"Cama matrimonial, Baño privado"),
        (6,1,6,400,"Cama matrimonial, Baño privado"),
        (9,1,9,450,"Cama matrimonial, Baño privado, Televisor"),
        (10,1,10,450,"Cama matrimonial, Baño privado, Televisor"),
        (11,1,11,450,"Cama matrimonial, Baño privado, Televisor"),
        (12,1,12,450,"Cama matrimonial, Baño privado, Televisor"),
        (13,1,13,450,"Cama matrimonial, Baño privado, Televisor"),
        (14,1,14,450,"Cama matrimonial, Baño privado, Televisor"),
        (15,1,15,400,"Cama matrimonial, Baño privado"),
        (16,1,16,500,"2 camas Individuales, Baño privado"),
        (17,1,17,400,"Cama matrimonial, Baño privado"),
        (18,1,18,400,"Cama matrimonial, Baño privado"),
        (7,2,7,550,"2 camas Individuales, Baño privado, Televisor"),
        (8,2,8,550,"2 camas Individuales, Baño privado, Televisor"),
        (19,2,19,700,"2 camas matrimoniales, Baño privado"),
        (20,2,20,900,"4 camas individuales, Baño privado"),
        (21,2,21,700,"3 camas individuales, Baño privado"),
        (22,2,22,550,"2 camas Individuales, Baño privado, Televisor"),
        (23,3,23,1100,"Cama Queen, Baño privado, Aire Acondicionado, Televisor"),
        (24,3,24,1100,"Cama Queen, Baño privado, Aire Acondicionado, Televisor"),
        (25,3,25,1100,"Cama Queen, Baño privado, Aire Acondicionado, Televisor"),
    ]
    for id_hab, id_cat, numero, precio, desc in habitaciones:
        cat = Categoria.objects.get(id_categoria=id_cat)
        Habitacion.objects.update_or_create(
            id=id_hab,
            defaults={
                'id_categoria': cat,
                'Numero_Habitacion': numero,
                'precio': precio,
                'Descripcion': desc,
                'Estado': True,
            }
        )

class Migration(migrations.Migration):
    dependencies = [
        ('Habitacion', '0002_habitacion_activo'),
    ]
    operations = [
        migrations.RunPython(seed_data),
    ]
