# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteSorteo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participante Sorteo',
                'verbose_name_plural': 'Participantes Sorteo',
                'db_table': 'participantes_sorteo',
            },
        ),
    ]
