# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(default='user', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=10)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_pasaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Seguridad.usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
