# Generated by Django 4.2.21 on 2026-05-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
