# Generated by Django 4.2.30 on 2026-05-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Habitacion', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('dias', models.IntegerField()),
                ('CantidadHuespedes', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(default='presencial', max_length=50)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Usuarios.cliente')),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Habitacion.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
    ]
